/**
 * Scraper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QVariantMap>
#include <QDebug>

#include "OAIScrapeApiHandler.h"
#include "OAIScrapeApiRequest.h"

namespace OpenAPI {

OAIScrapeApiHandler::OAIScrapeApiHandler(){

}

OAIScrapeApiHandler::~OAIScrapeApiHandler(){

}

void OAIScrapeApiHandler::scrape(QString filename, QString md5) {
    Q_UNUSED(filename);
    Q_UNUSED(md5);
    auto reqObj = qobject_cast<OAIScrapeApiRequest*>(sender());
    if( reqObj != nullptr )
    {
        OAIImagesResult res;
        reqObj->scrapeResponse(res);
    }
}


}
