/**
 * Scraper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIScrapeApiHandler_H
#define OAI_OAIScrapeApiHandler_H

#include <QObject>

#include "OAIErrorResult.h"
#include "OAIImagesResult.h"
#include <QString>

namespace OpenAPI {

class OAIScrapeApiHandler : public QObject
{
    Q_OBJECT

public:
    OAIScrapeApiHandler();
    virtual ~OAIScrapeApiHandler();


public slots:
    virtual void scrape(QString filename, QString md5);
    

};

}

#endif // OAI_OAIScrapeApiHandler_H
