/**
 * Scraper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIImagesResult.h
 *
 * 
 */

#ifndef OAIImagesResult_H
#define OAIImagesResult_H

#include <QJsonObject>

#include "OAIImagesResult_images.h"
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIImagesResult : public OAIObject {
public:
    OAIImagesResult();
    OAIImagesResult(QString json);
    ~OAIImagesResult() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getName() const;
    void setName(const QString &name);
    bool is_name_Set() const;
    bool is_name_Valid() const;

    QString getSystem() const;
    void setSystem(const QString &system);
    bool is_system_Set() const;
    bool is_system_Valid() const;

    OAIImagesResult_images getImages() const;
    void setImages(const OAIImagesResult_images &images);
    bool is_images_Set() const;
    bool is_images_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString name;
    bool m_name_isSet;
    bool m_name_isValid;

    QString system;
    bool m_system_isSet;
    bool m_system_isValid;

    OAIImagesResult_images images;
    bool m_images_isSet;
    bool m_images_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIImagesResult)

#endif // OAIImagesResult_H
