/**
 * Scraper
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIImagesResult_images.h
 *
 * 
 */

#ifndef OAIImagesResult_images_H
#define OAIImagesResult_images_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIImagesResult_images : public OAIObject {
public:
    OAIImagesResult_images();
    OAIImagesResult_images(QString json);
    ~OAIImagesResult_images() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getRLong() const;
    void setRLong(const QString &r_long);
    bool is_r_long_Set() const;
    bool is_r_long_Valid() const;

    QString getTall() const;
    void setTall(const QString &tall);
    bool is_tall_Set() const;
    bool is_tall_Valid() const;

    QString getHero() const;
    void setHero(const QString &hero);
    bool is_hero_Set() const;
    bool is_hero_Valid() const;

    QString getLogo() const;
    void setLogo(const QString &logo);
    bool is_logo_Set() const;
    bool is_logo_Valid() const;

    QString getIcon() const;
    void setIcon(const QString &icon);
    bool is_icon_Set() const;
    bool is_icon_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    QString r_long;
    bool m_r_long_isSet;
    bool m_r_long_isValid;

    QString tall;
    bool m_tall_isSet;
    bool m_tall_isValid;

    QString hero;
    bool m_hero_isSet;
    bool m_hero_isValid;

    QString logo;
    bool m_logo_isSet;
    bool m_logo_isValid;

    QString icon;
    bool m_icon_isSet;
    bool m_icon_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIImagesResult_images)

#endif // OAIImagesResult_images_H
